export const FEEDS = [
  { id: "si-001", url: "https://www.ansa.it/sito/ansait_rss.xml", cat: "Cronaca", name: "ANSA" },
  { id: "si-002", url: "https://www.tgcom24.mediaset.it/rss/homepage.xml", cat: "Cronaca", name: "TGCOM24" },
  { id: "si-003", url: "https://www.adnkronos.com/rss/home", cat: "Cronaca", name: "Adnkronos" },
  { id: "si-004", url: "https://news.google.com/rss/search?q=source:Reuters+World+News+when:24h&hl=en-US&gl=US&ceid=US:en", cat: "Mondo", name: "Reuters" },
  { id: "si-005", url: "https://feeds.bbci.co.uk/news/world/rss.xml", cat: "Mondo", name: "BBC News" },
  { id: "si-006", url: "https://www.lastampa.it/rss/torino.xml", cat: "Regioni", name: "La Stampa (Torino)" },
  { id: "si-007", url: "https://www.ilgiorno.it/rss/milano", cat: "Regioni", name: "Il Giorno" },
  { id: "si-008", url: "https://www.ilgazzettino.it/rss/veneto.xml", cat: "Regioni", name: "Il Gazzettino" },
  { id: "si-009", url: "https://www.ilrestodelcarlino.it/rss/bologna", cat: "Regioni", name: "Il Resto del Carlino" },
  { id: "si-010", url: "https://www.ilmessaggero.it/rss/roma.xml", cat: "Regioni", name: "Il Messaggero" },
  { id: "si-011", url: "https://www.ilmattino.it/rss/napoli.xml", cat: "Regioni", name: "Il Mattino" },
  { id: "si-012", url: "https://www.lasicilia.it/rss/cronaca", cat: "Regioni", name: "La Sicilia" },
  { id: "si-013", url: "https://www.unionesarda.it/rss", cat: "Regioni", name: "L'Unione Sarda" },
  // Scienza - Global & IT
  { id: "si-014", url: "https://www.nasa.gov/feed/", cat: "Scienza", name: "NASA" },
  { id: "si-015", url: "https://www.nature.com/nature.rss", cat: "Scienza", name: "Nature" },
  { id: "si-016", url: "https://www.sciencedaily.com/rss/all.xml", cat: "Scienza", name: "ScienceDaily" },
  { id: "si-017", url: "https://phys.org/rss-feed/", cat: "Scienza", name: "Phys.org" },
  { id: "si-018", url: "https://www.lescienze.it/rss/all/rss2.0.xml", cat: "Scienza", name: "Le Scienze" },
  { id: "si-019", url: "https://www.focus.it/rss", cat: "Scienza", name: "Focus.it" },
  { id: "si-020", url: "https://www.ansa.it/sito/ansait_scienza_rss.xml", cat: "Scienza", name: "ANSA Scienza" },
  { id: "si-021", url: "https://www.galileonet.it/feed/", cat: "Scienza", name: "Galileo" },
  { id: "si-022", url: "https://www.meteo.it/rss/news", cat: "Scienza", name: "Meteo.it" },
  { id: "si-023", url: "https://www.media.inaf.it/feed/", cat: "Scienza", name: "INAF" },
  // Tecnologia - IT
  { id: "si-024", url: "https://www.hdblog.it/feed/", cat: "Tecnologia", name: "HD Blog" },
  { id: "si-025", url: "https://www.dday.it/rss", cat: "Tecnologia", name: "DDay.it" },
  { id: "si-026", url: "https://www.tomshw.it/rss/", cat: "Tecnologia", name: "Tom's Hardware" },
  { id: "si-027", url: "https://www.wired.it/feed/", cat: "Tecnologia", name: "Wired IT" },
  { id: "si-028", url: "https://www.punto-informatico.it/feed/", cat: "Tecnologia", name: "Punto Informatico" },
  { id: "si-029", url: "https://leganerd.com/feed/", cat: "Tecnologia", name: "Lega Nerd" },
  { id: "si-030", url: "https://www.macitynet.it/feed/", cat: "Tecnologia", name: "Macitynet" },
  // Tecnologia - Global
  { id: "si-031", url: "https://www.theverge.com/rss/index.xml", cat: "Tecnologia", name: "The Verge" },
  { id: "si-032", url: "https://techcrunch.com/feed/", cat: "Tecnologia", name: "TechCrunch" },
  { id: "si-033", url: "https://www.technologyreview.com/feed/", cat: "Tecnologia", name: "MIT Tech Review" },
  { id: "si-034", url: "https://feeds.arstechnica.com/arstechnica/index", cat: "Tecnologia", name: "Ars Technica" },
  { id: "si-035", url: "https://openai.com/news/rss.xml", cat: "Tecnologia", name: "OpenAI Blog" },
  { id: "si-036", url: "https://blog.google/technology/ai/rss/", cat: "Tecnologia", name: "Google AI" },
  // Finanza - IT
  { id: "si-037", url: "https://www.ilsole24ore.com/rss/finanza.xml", cat: "Finanza", name: "Il Sole 24 Ore" },
  { id: "si-038", url: "https://www.milanofinanza.it/rss/notizie-milano-finanza.xml", cat: "Finanza", name: "Milano Finanza" },
  { id: "si-039", url: "https://www.wallstreetitalia.com/feed/", cat: "Finanza", name: "Wall Street Italia" },
  { id: "si-040", url: "https://quifinanza.it/feed/", cat: "Finanza", name: "QuiFinanza" },
  { id: "si-041", url: "https://www.borsaitaliana.it/borsa/notizie/rss/home.xml", cat: "Finanza", name: "Borsa Italiana" },
  { id: "si-042", url: "https://www.teleborsa.it/RSS/News.xml", cat: "Finanza", name: "Teleborsa" },
  // Finanza - Global
  { id: "si-043", url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15839069", cat: "Finanza", name: "CNBC (Finance)" },
  { id: "si-044", url: "https://www.ft.com/?format=rss", cat: "Finanza", name: "Financial Times" },
  { id: "si-045", url: "https://feeds.content.dowjones.io/public/rss/mw_topstories", cat: "Finanza", name: "MarketWatch" },
  { id: "si-046", url: "https://www.investopedia.com/rss/all", cat: "Finanza", name: "Investopedia" },
  // Sport
  { id: "si-047", url: "https://www.gazzetta.it/rss/home.xml", cat: "Sport", name: "Gazzetta" },
  { id: "si-048", url: "https://www.tuttosport.com/rss/calcio", cat: "Sport", name: "TuttoSport" },
  // Cultura - IT
  { id: "si-049", url: "https://www.ilpost.it/cultura/feed/", cat: "Cultura", name: "Il Post (Cultura)" },
  { id: "si-050", url: "https://www.minimaetmoralia.it/wp/feed/", cat: "Cultura", name: "Minima & Moralia" },
  { id: "si-051", url: "https://www.artribune.com/feed/", cat: "Cultura", name: "Artribune" },
  { id: "si-052", url: "https://arte.sky.it/feed", cat: "Cultura", name: "Sky Arte" },
  { id: "si-053", url: "https://www.finestresullarte.info/rss/news.xml", cat: "Cultura", name: "Finestre sull'Arte" },
  { id: "si-054", url: "https://www.lindiceonline.com/feed/", cat: "Cultura", name: "L'Indice" },
  { id: "si-055", url: "https://www.doppiozero.com/feed", cat: "Cultura", name: "Doppiozero" },
  // Cultura - Global
  { id: "si-056", url: "https://www.newyorker.com/feed/culture", cat: "Cultura", name: "The New Yorker (Culture)" },
  { id: "si-057", url: "https://www.openculture.com/feed", cat: "Cultura", name: "Open Culture" },
  { id: "si-058", url: "https://www.bbc.com/culture/feed.rss", cat: "Cultura", name: "BBC Culture" },
  // Salute
  { id: "si-059", url: "https://news.google.com/rss/search?q=Fondazione+Veronesi+when:7d&hl=it&gl=IT&ceid=IT:it", cat: "Salute", name: "Fondazione Veronesi" },
  { id: "si-060", url: "https://www.dica33.it/rss/news.xml", cat: "Salute", name: "Dica33" },
  { id: "si-061", url: "http://www.quotidianosanita.it/rss/rss.php", cat: "Salute", name: "Quotidianosanità" },
  { id: "si-062", url: "https://www.iss.it/news/-/asset_publisher/987654321/rss", cat: "Salute", name: "ISS News" },
  { id: "si-063", url: "https://www.ansa.it/canale_saluteebenessere/notizie/sanita_rss.xml", cat: "Salute", name: "Salute Lab (ANSA)" },
  { id: "si-064", url: "https://www.humanitasalute.it/feed/", cat: "Salute", name: "Humanitas Salute" },
  { id: "si-065", url: "https://www.medicalnewstoday.com/rss", cat: "Salute", name: "Medical News Today" },
  { id: "si-066", url: "https://www.who.int/rss-feeds/news-english.xml", cat: "Salute", name: "WHO (OMS)" },
  { id: "si-067", url: "https://www.sciencedaily.com/rss/health_medicine.xml", cat: "Salute", name: "ScienceDaily (Health)" },
  { id: "si-068", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6P0M6qRz6f0M6qRz6f0M6q", cat: "Salute", name: "Pillole di Salute" },
  { id: "si-069", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCX0S2H6_i9P_Z_I8J_8J_A", cat: "Salute", name: "Ospedale Bambino Gesù" },
  // Gaming - IT & Global (Assigned to Tecnologia for Smartinfo)
  { id: "si-070", url: "https://www.eurogamer.it/feed", cat: "Tecnologia", name: "Eurogamer IT" },
  { id: "si-071", url: "https://www.spaziogames.it/feed/", cat: "Tecnologia", name: "SpazioGames" },
  { id: "si-072", url: "https://www.thegamesmachine.it/feed/", cat: "Tecnologia", name: "TGM" },
  { id: "si-073", url: "https://www.tomshw.it/games/feed/", cat: "Tecnologia", name: "Tom's Hardware IT" },
  { id: "si-074", url: "https://player.it/feed/", cat: "Tecnologia", name: "Player.it" },
  { id: "si-075", url: "https://hypegame.it/feed/", cat: "Tecnologia", name: "HypeGame" },
  { id: "si-076", url: "https://www.vgmag.it/feed/", cat: "Tecnologia", name: "Vgmag.it" },
  { id: "si-077", url: "https://topgamesitalia.com/feed/", cat: "Tecnologia", name: "Top Games Italia" },
  { id: "si-078", url: "https://4news.it/feed/", cat: "Tecnologia", name: "4News.it" },
  { id: "si-079", url: "https://gamesurf.tiscali.it/feed/rss", cat: "Tecnologia", name: "Gamesurf" },
  { id: "si-080", url: "https://www.gamescore.it/feed/", cat: "Tecnologia", name: "GameScore" },
  { id: "si-081", url: "https://toucharcade.com/feed/", cat: "Tecnologia", name: "TouchArcade" },
  { id: "si-082", url: "https://www.pocketgamer.com/rss", cat: "Tecnologia", name: "Pocket Gamer" },
  { id: "si-083", url: "https://www.androidcentral.com/gaming/rss.xml", cat: "Tecnologia", name: "Android Central Gaming" },
  { id: "si-084", url: "https://www.droidgamers.com/feed/", cat: "Tecnologia", name: "Droid Gamers" },
  { id: "si-085", url: "https://www.pockettactics.com/feed", cat: "Tecnologia", name: "Pocket Tactics" },
  { id: "si-086", url: "https://www.videogameschronicle.com/feed/", cat: "Tecnologia", name: "VGC" },
  { id: "si-087", url: "https://www.androidworld.it/tag/giochi-android/feed/", cat: "Tecnologia", name: "AndroidWorld IT" },
  { id: "si-088", url: "https://www.iphoneitalia.com/tag/giochi-iphone/feed/", cat: "Tecnologia", name: "iPhoneItalia IT" },
  { id: "si-089", url: "https://www.macitynet.it/ios/giochi-ios/feed/", cat: "Tecnologia", name: "Macitynet IT" },
  { id: "si-090", url: "https://9to5google.com/guides/cloud-gaming/feed/", cat: "Tecnologia", name: "9to5Google Cloud" }
];
